version: '2'
volumes:
  mysql_volume:
    driver: local
  joomla_volume:
    driver: local
  
services:
  joomla:
    build: joomla/
    ports:
     - 127.0.0.1:8001:80
    depends_on:
     - joomladb
     - sshd
    volumes:
     - joomla_volume:/var/www/html
    restart: always
    environment:
      JOOMLA_DB_HOST: "joomladb:3306"
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    volumes:
     - mysql_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  sshd:
    image: rastasheep/ubuntu-sshd
    volumes:
     - joomla_volume:/root/joomla
    ports:
     - 127.0.0.1:30000:22
    restart: always

  backup: &backup_restore
    image: boombatower/docker-backup
    volumes_from:
     - joomla
     - joomladb
    volumes:
     - ./backup:/backup
    entrypoint: bash -c "/root/bin/backup.sh backup $$(date +%Y%m%d%H%M%S).tar.xz"
  
  restore:
    <<: *backup_restore
    volumes:
     - ./:/backup
    entrypoint: 
     - /root/bin/backup.sh
     - restore

